name: "JUnit+Clover publisher"
description: "Merges results from junit.xml and clover.xml and publishes as a comment in pull request"
author: "Norbert Kowalik"
branding:
  icon: align-justify
  color: purple
inputs:
  github_token:
    description: "GitHub token"
    required: true
    default: ""
  clover:
    description: "Path to Clover file"
    required: true
    default: "clover.xml"
  junit:
    description: "Path/glob to JUnit file"
    required: true
    default: "junit.xml"
outputs: {}
runs:
  using: "docker"
  image: "Dockerfile"